# Generated by Django 3.1.6 on 2021-02-09 03:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 2, 9, 3, 9, 37, 317227, tzinfo=utc), verbose_name='Дата создания')),
            ],
        ),
    ]
