# Generated by Django 3.1.6 on 2021-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210209_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=250, verbose_name='URL'),
        ),
    ]
